REChase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teams.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bit1/urls.py
from django.urls import path
from . import views

app_name = 'bit1'
urlpatterns = [
    path('', views.home, name='home'),
]

teams/urls.py
from django.urls import path, include
from . import views

app_name = 'teams'
urlpatterns = [
    path('', views.home, name='home'),
    path('get_team/', views.get_team, name='get-team'),
    path('create-team/', views.createTeam, name='create-team'),
    path('join-team/', views.joinTeam, name='join-team'),
    path('accept-team-mate/', views.acceptTeamMateView, name='accept-teammate'),
    path('complete-profile/', views.profileCompleteView, name='complete-profile'),
    path('scoreboard/', views.scoreboardView, name='scoreboard'),
    path('rules/', views.rules, name='rules'),
    path('playerdetail/', views.playerdetail, name='teamdetail'),
    path('detailedscore/',views.detailedScoreboardView, name='detailedscore'),
    path('chase/', views.get_level, name='get-level'),
    path('chase/1/', views.start_hunt, name='start_hunt'),

]

teams/models.py
import datetime
import json

from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import make_aware


class Team(models.Model):
    name = models.CharField(max_length=128, null=True, unique=True)
    code = models.CharField(max_length=128, null=True, blank=True)
    member_count = models.IntegerField(default=0, null=True)
    current_level = models.IntegerField(default=0, null=True)
    current_question = models.IntegerField(default=-1, null=True)
    question = models.CharField(max_length=255, null=True, blank=True, default='-1')
    answers = models.CharField(max_length=8192, null=True, blank=True, default='{}')
    score = models.IntegerField(default=0, null=True)
    rank = models.IntegerField(default=0, null=True)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def answerCorr(self, curr_lvl=1, answer=None):
        self.current_level = curr_lvl + 1
        self.current_question = -1
        self.question = '-1'
        self.score = self.score + 10
        if curr_lvl == 1:
            temp = {}
        else:
            temp = json.loads(self.answers)
        temp[curr_lvl] = answer
        self.answers = json.dumps(temp)
        self.timestamp = make_aware(datetime.datetime.now())
        self.save()

    

    def specialCipher(self, answer):
        temp = json.loads(self.answers)

        if self.current_question == 1:
            temp[str(self.current_level)] = {}
        temp[str(self.current_level)][str(self.current_question)] = answer

        self.answers = json.dumps(temp)
        if self.current_question == 7:
            self.current_level = self.current_level + 1
            self.current_question = -1
            self.question = '-1'
            self.score = self.score + 10
            self.timestamp = make_aware(datetime.datetime.now())

        else:
            self.current_question = self.current_question + 1

        self.save()




class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, null=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    phone = models.CharField(max_length=13, null=True)
    gender = models.CharField(max_length=2,
                              choices=(
                                  ('M', 'Male'),
                                  ('F', 'Female'),
                                  ('O', 'Others'),
                              ),
                              default='M')
    college = models.CharField(max_length=128, default='NIT Durgapur')
    team_code = models.CharField(max_length=128, null=True, blank=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    accepted = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name

teams/forms.py
from django import forms

from .models import (
    Team,
    Player
)

class TeamCreationForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name']


class ProfileFillForm(forms.ModelForm):
    phone = forms.CharField(max_length=13, min_length=10)

    class Meta:
        model = Player
        fields = ['name', 'phone', 'gender', 'college']

teams/views.py
from django.shortcuts import render, redirect
from . import models
import datetime
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .decorators import team_required
from .forms import (
    TeamCreationForm,
    ProfileFillForm,
)
from .utils import makeCode
from django.conf import settings

def save_profile(backend, user, response, *args, **kwargs):
    # print(response)
    if backend.name == 'google-oauth2':
        profile = user
        try:
            Player = models.Player.objects.get(user=profile)
        except:
            Player = models.Player(user=profile)
            Player.timestamp = datetime.datetime.now()
            try:
                Player.name = response.get('name')
                Player.email = response.get('email')
            except:
                Player.name = response.get('given_name') + " " + response.get('family_name')
            Player.save()


def home(request):
    user = request.user
    if not user.is_authenticated:
        # For managing event Wait and Finish
        context = {}
        if datetime.datetime.now() < settings.START_TIME:
            context = {'wait': 1, 'cur_time': datetime.datetime.now(),
                       'start_time': settings.START_TIME}
        elif datetime.datetime.now() > settings.END_TIME:
            context['finish'] = 1
        else:
            context['started'] = 1
        return render(request, 'teams/base_menu.html', context)

    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect('teams:complete-profile')
    if profile.team is None or profile.accepted == 0:
        return render(request, 'teams/no_team.html', {})
    team = models.Team.objects.get(id=profile.team.pk)
    everyone = models.Player.objects.filter(team=team.pk)
    team_players = everyone.filter(accepted=1)
    context = {'team': team, 'profile': profile, 'players': team_players, 'max_level': settings.FINAL_LEVEL}
    if team.member_count < 5:
        applicants = everyone.filter(accepted=0)
        context['applicants'] = applicants

    # For managing event Wait and Finish  
    if datetime.datetime.now() < settings.START_TIME:
        context['wait'] = 1
        context['cur_time'] = datetime.datetime.now()
        context['start_time'] = settings.START_TIME
    elif datetime.datetime.now() > settings.END_TIME:
        context['finish'] = 1
    else:
        context['started'] = 1

    return render(request, 'teams/teamHome.html', context)

@login_required
@team_required
def get_level(request):
    user = request.user
    profile = models.Player.objects.get(user=user)

    team = models.Team.objects.get(id=profile.team.pk)
    level = team.current_level
    if level > settings.FINAL_LEVEL:
        return redirect('teams:scoreboard')

    return redirect(request.path + str(1))

@login_required
@team_required
def start_hunt(request):
    return render(request,'teams/start_location.html')



@login_required
def get_team(request):
    return render(request, 'teams/no_team.html', {})


@login_required
def createTeam(request):
    context = {}
    user = request.user
    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect('teams:complete-profile')
    form = TeamCreationForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        code = makeCode()
        obj.code = code
        obj.member_count = 1
        obj.save()
        curr_user = models.Player.objects.get(user=user)
        curr_user.team = obj
        curr_user.team_code = code
        curr_user.accepted = 1
        curr_user.save()
        return redirect('teams:home')

    context['form'] = form
    return render(request, 'teams/teamCreation.html', context=context)


@login_required
def joinTeam(request):
    context = {}
    user = request.user
    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect('teams:complete-profile')
    if profile.accepted == 1 and profile.team is not None:
        return redirect('teams:home')
    if request.method == 'POST':
        code = request.POST.get('code', -1)
        team = models.Team.objects.filter(code=code).first()
        if not team:
            context['wrong_code'] = 'Invalid code entered.'
            return render(request, 'teams/teamJoin.html', context=context)
        if team.member_count >= 5:
            context['team_full'] = 'Team is full.'
            return render(request, 'teams/teamJoin.html', context=context)
        profile.team = team
        profile.team_code = team.code
        profile.accepted = 0
        profile.save()
        context['sent'] = 1
        return render(request, 'teams/no_team.html', context=context)

    return render(request, 'teams/teamJoin.html', context=context)


@login_required
def profileCompleteView(request):
    context = {}
    user = request.user
    profile = models.Player.objects.get(email=user.email)
    form = ProfileFillForm(request.POST or None)
    if form.is_valid():
        form.clean()
        profile.name = form.cleaned_data['name']
        profile.phone = form.cleaned_data['phone']
        profile.gender = form.cleaned_data['gender']
        profile.college = form.cleaned_data['college']
        profile.save()
        return redirect('teams:home')
    context['form'] = form
    return render(request, 'teams/createProfile.html', context)


@login_required
@team_required
def leaveTeamView(request):  # needs to be removed
    context = {}
    user = request.user
    profile = models.Player.objects.get(user=user)
    team = models.Team.objects.get(id=profile.team.pk)
    if request.method == 'POST':
        if team.member_count == 1:
            team.delete()
        else:
            team.member_count = team.member_count - 1
            team.save()
        profile.team = None
        profile.team_code = None
        profile.save()
        return redirect('teams:get-team')
    context['team'] = team
    context['profile'] = profile
    return render(request, 'teams/confirmLeave.html', context)


@login_required
def acceptTeamMateView(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('/oauth/login/google-oauth2/')

    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect(reverse_lazy('teams:complete-profile'))

    if profile.accepted == 0 or profile.team is None:
        return redirect(reverse_lazy('teams:get-team'))

    context = {}
    owner = models.Player.objects.get(user=request.user)
    team = models.Team.objects.get(pk=owner.team.id)
    applicantId = int(request.POST.get('ID'))
    verdict = request.POST.get('verdict')
    applicant = models.Player.objects.get(id=applicantId)
    if verdict == 'Reject':
        applicant.team = None
        applicant.save()
    elif verdict == 'Accept':
        if team.member_count >= 5:
            context['team_full'] = 'Team is full.'
            return redirect('teams:home')
        applicant.accepted = 1
        applicant.team_code = team.code
        applicant.save()
        team.member_count = team.member_count + 1
        team.save()
    return redirect('teams:home')


def scoreboardView(request):
    context = {'cur_time': datetime.datetime.now(), 'start_time': settings.START_TIME}

    cur_rank = 0
    try:
        all_teams = models.Team.objects.all()
        qs = all_teams.order_by('-score', 'timestamp')
        for pl in qs:
            pl.rank = cur_rank
        context['qs'] = qs
    except:
        context['wrong'] = 1
    if datetime.datetime.now() < settings.START_TIME:
        context['wait'] = 1
    return render(request, 'teams/leaderBoard.html', context)


def rules(request):
    context = {}
    return render(request, 'teams/rules.html', context)


def playerdetail(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("teams:home"))
    if not request.user.is_superuser:
        return redirect(reverse_lazy("teams:home"))
    all_players = models.Player.objects.all().order_by('-team_code', 'timestamp')
    context = {'players': all_players}
    return render(request, 'teams/playerdetail.html', context)

def detailedScoreboardView(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("teams:home"))
    if not request.user.is_superuser:
        return redirect(reverse_lazy("teams:home"))
    
    context = {'cur_time': datetime.datetime.now(), 'start_time': settings.START_TIME}

    cur_rank = 0
    
    all_teams = models.Team.objects.all()
    qs = all_teams.order_by('-score', 'timestamp')
    allplayers = models.Player.objects.all()
    qp = []
    for pl in qs:
        pl.rank = cur_rank
        tc = pl.code
        sz = pl.member_count
        players = []
        for eachplayer in allplayers:
            teamcode = eachplayer.team_code
            if teamcode == tc:
                players.append({
                    "name" : eachplayer.name,
                    "email" : eachplayer.email,
                })
        cnt_player = 1 
        player1 = "-"
        player2 = "-"
        email1 = "-"
        email2 = "-"
        for xx in players:
            if cnt_player==1:
                player1 = xx["name"]
                email1 = xx["email"]
            if cnt_player==2:
                player2 = xx["name"]
                email2 = xx["email"]
            cnt_player+=1
        
        qp.append(
            {
                "rank" : cur_rank,
                "name" : pl.name,
                "score" : pl.score,
                "ques" : pl.current_level,
                "player1" : player1,
                "player2" : player2,
                "email1" : email1,
                "email2" : email2
            }
        )
        # cur_rank += 1
        context['qp'] = qp
        leveldetail=[]
        for i in range(1,13):
            curr_level = i

teams/templates/teams/snippets/navbar.html
{% load static %} {% load teams_extra_filters %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width,initial-sclae=1.0" />
		<title>REChase</title>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
		/>
		<link
			href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
			rel="stylesheet"
		/>
		<link
			href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap"
			rel="stylesheet"
		/>
		<link rel="preconnect" href="https://fonts.gstatic.com" />
		<link
			href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap"
			rel="stylesheet"
		/>

		<script src="https://kit.fontawesome.com/a076d05399.js"></script>
		<style>
			* {
				margin: 0;
				padding: 0;
				box-sizing: border-box;
				outline: none;
			}
			body {
				min-height: 100vh;

				background-color: black;
				background-image: url("{% static 'teams/images/mars_gif1.gif' %}");
				background-repeat: no-repeat;
				background-size: cover;
				font-family: Open sans;
			}

			.navbar {
				position: fixed top;
				width: 100%;
				z-index: 2;
				padding: 25px 30px;
				transition: all 0.3s ease;
			}
			.navbar.sticky {
				background: #ff009d59;
				padding: 10px 0;
				box-shadow: 0px 3px 5px 0px rgba(0, 0, 0, 0.1);
			}
			.navbar .content1 {
				display: flex;
				align-items: center;
				justify-content: space-between;
			}
			.navbar .logo a {
				text-shadow: 0 0 4px #ff009d;
				color: #fff;
				font-family: "Share Tech", sans-serif !important;
				font-size: 30px;
				font-weight: 600;
				text-decoration: none;
			}
			.navbar .menu-list {
				display: inline-flex;
			}
			.menu-list li {
				list-style: none;
			}
			.menu-list li a {
				color: #fff;
				padding: 5px;
				border-radius: 10%;
				font-family: "Share Tech", sans-serif !important;
				font-size: 18px;
				font-weight: 800;
				margin-left: 25px;
				text-decoration: none;
				transition: all 0.3s ease;
			}
			.menu-list li a:hover {
				border: solid 1px #E97957;
				box-shadow: 0 0 5px #E97957, 0 0 25px #E97957;
				border-radius: 9px;
			}
			.icon {
				color: #fff;
				font-size: 20px;
				cursor: pointer;
				display: none;
			}
			.menu-list .cancel-btn {
				position: absolute;
				right: 30px;
				top: 20px;
			}
			@media (max-width: 1230px) {
				.content {
					padding: 0 60px;
				}
			}
			@media (max-width: 1100px) {
				.content {
					padding: 0 40px;
				}
			}
			@media (max-width: 900px) {
				.content {
					padding: 0 30px;
				}
			}
			@media (max-width: 868px) {
				.icon {
					display: block;
				}
				.icon.hide {
					display: none;
				}
				.icon:hover {
					color: #050801;
				}
				.navbar .menu-list {
					position: fixed;
					height: 100vh;
					width: 100%;
					max-width: 400px;
					left: -100%;
					top: 0px;
					display: block;
					padding: 40px 0;
					text-align: center;
					background-color: rgba(0, 0, 0, 0.8);
					backdrop-filter: blur(5px);
					/* background-image: linear-gradient(to left, #d1c4c4 0%, #313030 74%); */
					transition: all 0.3s ease;
				}
				.navbar.show .menu-list {
					left: 0%;
				}
				.navbar .menu-list li {
					margin-top: 45px;
				}
				.navbar .menu-list li a {
					font-size: 23px;
					margin-left: -100%;
					transition: 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
				}
				.navbar.show .menu-list li a {
					margin-left: 0px;
				}
			}
			@media (max-width: 380px) {
				.navbar .logo a {
					font-size: 27px;
				}
			}

			/*cursor animation*/
			.cursor {
				position: fixed;
				width: 50px;
				height: 50px;
				border: 1px solid #E97957;
				border-radius: 50%;
				left: 0;
				right: 0;
				pointer-events: none;
				transform: translate(-50%, -50%);
				transition: 0.1s;
			}
			.cursor2 {
				position: fixed;
				width: 8px;
				height: 8px;
				background-color: #D63629;
				border-radius: 50%;
				left: 0;
				top: 0;
				pointer-events: none;
				transform: translate(-50%, -50%);
				transition: 0.3s;
			}
		</style>
	</head>
	<body>
		<nav class="navbar">
			<div class="content1">
				<div class="logo">
					<a href="{% url 'teams:home' %}"
						><img
							style="height: 50px; width: 65px; border: none; margin-right: 5px"
							src="{% static 'teams/images/final_logo.png' %}"
					/></a>
					<a href="http://arhn.co.in" target="blank"
						><img
							style="height: 50px; width: 50px; border: none; margin-right: 5px"
							src="{% static 'teams/images/logo_2023.png' %}"
					/></a>
				</div>

				<ul class="menu-list">
					<div class="icon cancel-btn">
						<i class="fas fa-times"></i>
					</div>
					{% if user.is_authenticated %}
					<li>
						<a style="text-decoration: none" href="{% url 'teams:home' %}"
							>{% get_the_username user %}</a
						>
					</li>
					{% endif %} 
					{% if "/rules/" == request.path %}
					<li><a href="{% url 'teams:home' %}">Home</a></li>
					<li><a href="{% url 'teams:scoreboard' %}">Leaderboard</a></li>
					{% elif "/scoreboard/" == request.path %}
					<li><a href="{% url 'teams:home' %}">Home</a></li>
					<li><a href="{% url 'teams:rules' %}">Rules</a></li>
					{% else %}
					<li><a href="{% url 'teams:rules' %}">Rules</a></li>
					<li><a href="{% url 'teams:scoreboard' %}">Leaderboard</a></li>
					{% endif %} {% if user.is_authenticated %}
					<li>
						<a href="{% url 'logout' %}?next={% url 'teams:home' %}">Logout</a>
					</li>
					{% else %}
					<li>
						<a
							href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}"
							>Login</a
						>
					</li>
					{% endif %}
				</ul>
				<div class="icon menu-btn">
					<i class="fas fa-bars"></i>
				</div>
			</div>
		</nav>

		<div class="cursor"></div>
		<div class="cursor2"></div>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
		<!--letteringjs-->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/lettering.js/0.7.0/jquery.lettering.min.js"></script>
		<!--animiejs-->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>

		<script>
			const body = document.querySelector("body");
			const navbar = document.querySelector(".navbar");
			const menuBtn = document.querySelector(".menu-btn");
			const cancelBtn = document.querySelector(".cancel-btn");
			menuBtn.onclick = () => {
				navbar.classList.add("show");
				menuBtn.classList.add("hide");
				body.classList.add("disabled");
			};
			cancelBtn.onclick = () => {
				body.classList.remove("disabled");
				navbar.classList.remove("show");
				menuBtn.classList.remove("hide");
			};
			window.onscroll = () => {
				this.scrollY > 20
					? navbar.classList.add("sticky")
					: navbar.classList.remove("sticky");
			};
		</script>
		<!--cursor script-->
		<script>
			var cursor = document.querySelector(".cursor");
			var cursor2 = document.querySelector(".cursor2");
			document.addEventListener("mousemove", function (e) {
				cursor.style.cssText = cursor2.style.cssText =
					"left: " + e.clientX + "px; top: " + e.clientY + "px;";
			});
		</script>
	</body>
</html>