REChase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teams.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bit1/urls.py
from django.urls import path
from . import views

app_name = 'bit1'
urlpatterns = [
    path('', views.home, name='home'),
]

cars2/urls.py
from django.urls import path
from . import views

app_name = 'cars2'
urlpatterns = [
    path('', views.home, name='home'),
]

catalan11/urls.py
from django.urls import path
from . import views

app_name = 'catalan11'
urlpatterns = [
    path('', views.home, name='home'),
]

chess4/urls.py
from django.urls import path
from . import views

app_name = 'chess4'
urlpatterns = [
    path('', views.home, name='home'),
]

ciphers/urls.py
from django.urls import path
from . import views

app_name = 'ciphers'
urlpatterns = [
    path('', views.home, name='home'),
]

coordinates/urls.py
from django.urls import path
from . import views

app_name = 'coordinates'
urlpatterns = [
    path('', views.home, name='home'),
]

evan10/urls.py
from django.urls import path
from . import views

app_name = 'evan10'
urlpatterns = [
    path('', views.home, name='home'),
]

guessing/urls.py
from django.urls import path
from . import views

app_name = 'guessing'
urlpatterns = [
    path('', views.home, name='home'),
]

ideone/urls.py
from django.urls import path
from . import views

app_name = 'ideone'
urlpatterns = [
    path('', views.home, name='home'),
]

jumble/urls.py
from django.urls import path
from . import views

app_name = 'jumble'
urlpatterns = [
    path('', views.home, name='home'),
]

magicalbox/urls.py
from django.urls import path
from . import views

app_name = 'magicalbox'
urlpatterns = [
    path('', views.home, name='home'),
]

morse8/urls.py
from django.urls import path
from . import views

app_name = 'morse8'
urlpatterns = [
    path('', views.home, name='home'),
]

museum5/urls.py
from django.urls import path
from . import views

app_name = 'meseum5'
urlpatterns = [
    path('', views.home, name='home'),
]

nft1/urls.py
from django.urls import path
from . import views

app_name = 'nft1'
urlpatterns = [
    path('', views.home, name='home'),
]

palindrome3/urls.py
from django.urls import path
from . import views

app_name = 'palindrome3'
urlpatterns = [
    path('', views.home, name='home'),
]

pattern9/urls.py
from django.urls import path
from . import views

app_name = 'pattern9'
urlpatterns = [
    path('', views.home, name='home'),
]

prefixSum/urls.py
from django.urls import path
from . import views

app_name = 'prefixSum'
urlpatterns = [
    path('', views.home, name='home'),
    path('firstTime/', views.firstTime, name='firstTime'),
]

spell7/urls.py
from django.urls import path
from . import views

app_name = 'spell7'
urlpatterns = [
    path('', views.home, name='home'),
]

sudoku/urls.py
from django.urls import path
from . import views

app_name = 'sudoku'
urlpatterns = [
    path('', views.home, name='home'),
]

teams/urls.py
from django.urls import path, include
from . import views

app_name = 'teams'
urlpatterns = [
    path('', views.home, name='home'),
    path('get_team/', views.get_team, name='get-team'),
    path('create-team/', views.createTeam, name='create-team'),
    path('join-team/', views.joinTeam, name='join-team'),
    path('accept-team-mate/', views.acceptTeamMateView, name='accept-teammate'),
    path('complete-profile/', views.profileCompleteView, name='complete-profile'),
    path('scoreboard/', views.scoreboardView, name='scoreboard'),
    path('rules/', views.rules, name='rules'),
    path('playerdetail/', views.playerdetail, name='teamdetail'),
    path('detailedscore/',views.detailedScoreboardView, name='detailedscore'),
    path('chase/', views.get_level, name='get-level'),
    path('chase/1/', views.start_hunt, name='start_hunt'),

]

wordRank/urls.py
from django.urls import path
from . import views

app_name = 'wordRank'
urlpatterns = [
    path('', views.home, name='home'),
]

xor12/urls.py
from django.urls import path
from . import views

app_name = 'xor12'
urlpatterns = [
    path('', views.home, name='home'),
]

ciphers/models.py
from django.db import models
import datetime
# Create your models here.


def upload_location(instance, filename, **kwargs):
    file_path = 'ciphers/{stage}/{time}-{filename}'.format(
        stage=str(instance.id), time=str(datetime.datetime.now().strftime("%H%M%S%f")), filename=filename
    )
    print(file_path)
    return file_path


class Cipher(models.Model):
    question=models.TextField(blank=True)
    answer=models.CharField(max_length=256,blank=False)
    crossword = models.ImageField(
        upload_to=upload_location,
        null=True
    )
    # image2 = models.ImageField(upload_to=upload_location,
    #                            null=True,
    #                            blank=True,
    #                            )
    hint = models.FileField(upload_to=upload_location,
                            null=True,
                            blank=True
                            )
    correct = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    accuracy = models.FloatField(default=0)
    modal = models.TextField(null=True, blank=True)

    def __str__(self):
        return 'Cipher question- {}'.format(self.id)

    def calcAccu(self):
        self.accuracy=round(self.correct / (float(self.correct + self.wrong)), 2) * 100

    def answered(self,right=1):
        if right:
            self.correct=self.correct+1
        else:
            self.wrong=self.wrong+1
        self.calcAccu()
        self.save()

ciphers/forms.py
from django import forms


class AnswerForm(forms.Form):
    answer = forms.CharField(max_length=256)


class SpecialForm(forms.Form):
    answer1=forms.CharField(max_length=64,required=True)
    answer2=forms.CharField(max_length=64,required=True)
    answer3=forms.CharField(max_length=64,required=True)

ciphers/views.py
from django.shortcuts import render, redirect
from teams.models import Team, Player
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import AnswerForm, SpecialForm
from .models import Cipher
from teams.decorators import team_required

THIS_LEVEL = 10
FINAL_ANSWERS = ('BABIES', 'BLAST', 'ANACONDA')


@login_required
@team_required
def home(request):
    user = request.user
    context = {}
    profile = Player.objects.get(user=user)
    team = Team.objects.get(id=profile.team.pk)

    if team.current_level != THIS_LEVEL:
        return redirect(reverse_lazy('teams:get-level'))

    if str(team.current_question) == '-1':
        team.current_question = 1
        team.save()
    q_no = team.current_question
    question = Cipher.objects.get(id=q_no)
    if q_no != 6:
        answer = AnswerForm(request.POST or None)
    else:
        answer = SpecialForm(request.POST or None)
    context['answer'] = answer
    context['profile'] = profile
    context['team'] = team
    context['question'] = question
    corr_ans = question.answer.upper()
    # print(corr_ans)
    if request.method == 'POST':
        if answer.is_valid():
            if q_no == 6:
                ans1 = answer.cleaned_data['answer1'].upper()
                ans2 = answer.cleaned_data['answer2'].upper()
                ans3 = answer.cleaned_data['answer3'].upper()
                corr_ans = FINAL_ANSWERS
                ans = (ans1, ans2, ans3)
            else:
                ans = answer.cleaned_data['answer'].upper()
            if corr_ans == ans:
                question.answered(right=1)
                if q_no == 7:
                    team.answerCorr(THIS_LEVEL, corr_ans)
                    return redirect(reverse_lazy('teams:get-level'))
                else:
                    team.specialCipher(corr_ans)
                    return redirect('teams:ciphers:home')

            else:
                question.answered(right=0)
                context['wrong'] = 1

    return render(request, 'ciphers/question.html', context)

ciphers/templates/ciphers/question.html
{% include 'teams/base_bootstrap.html' %} {% block content %}
<link
	href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap"
	rel="stylesheet"
/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link
	href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap"
	rel="stylesheet"
/>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<style>
	@import url("https://fonts.googleapis.com/css2?family=Niconne&display=swap");
	@import url("https://fonts.googleapis.com/css2?family=Metrophobic&display=swap");

	.pigpen {
		width: 400px;
		height: 115px;
	}

	.imgg {
		width: 30%;
		height: auto;
		display: block;
		margin-left: auto;
		margin-right: auto;
	}

	@media (max-width: 500px) {
		.imgg {
			width: 85%;
			display: block;
			margin-left: auto;
			margin-right: auto;
		}
		.pigpen {
			width: 300px;
			height: 100px;
		}
	}

	@media (min-width: 501px) and (max-width: 1000px) {
		.imgg {
			width: 65%;
			display: block;
			margin-left: auto;
			margin-right: auto;
		}
	}

	input[type="submit"] {
		background: -webkit-gradient(
			linear,
			left bottom,
			left top,
			from(#000000),
			to(#262626)
		);
		background: -webkit-linear-gradient(bottom, #000000, #262626);
		background: -moz-linear-gradient(bottom, #000000, #262626);
		background: -o-linear-gradient(bottom, #000000, #262626);
		background: linear-gradient(0deg, #000000, #262626);
		backdrop-filter: blur(10px);
		padding: 25px 105px;
		border: none;
		border-radius: 10px;
		cursor: pointer;
		box-shadow: 0 0 1rem 0 rgba(0, 0, 0, 0.4);
	}

	input[type="text"],
	select,
	textarea {
		height: 40px;
		width: 250px;

		padding: 9px;
		border: 2px solid #fff;
		border-radius: 10px;
		box-sizing: border-box;
		margin-top: 6px;
		margin-bottom: 16px;
		resize: vertical;
		color: #fff;

		background: -webkit-gradient(
			linear,
			left bottom,
			left top,
			from(#000000),
			to(#262626)
		);
		background: -webkit-linear-gradient(bottom, #000000, #262626);
		background: -moz-linear-gradient(bottom, #000000, #262626);
		background: -o-linear-gradient(bottom, #000000, #262626);
		background: linear-gradient(0deg, #000000, #262626);
		backdrop-filter: blur(10px);
	}
</style>

<div
	class="card text-center"
	style="background: rgba(1, 2, 3, 0.6); padding: 30px 30px"
>
	{% if question.modal %}
	<div class="card-header">
		<!-- Button trigger modal -->
		<button
			type="button"
			class="btn btn-info"
			data-toggle="modal"
			data-target="#exampleModalLong"
			style="margin-top: 10px"
		>
			Hints
		</button>
		<br />
		<br />

		<!-- Modal -->
		<div
			class="modal fade"
			id="exampleModalLong"
			tabindex="-1"
			role="dialog"
			aria-labelledby="exampleModalLongTitle"
			aria-hidden="true"
		>
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLongTitle">Hints</h5>
						<button
							type="button"
							class="close"
							data-dismiss="modal"
							aria-label="Close"
						>
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">{{ question.modal | safe }}</div>
					<div class="modal-footer">
						<button
							type="button"
							class="btn btn-secondary"
							data-dismiss="modal"
						>
							Close
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endif %}
	<div class="card-body" style="color: #fff">
		<p class="card-text" style="color: #fff">
			<img
				class="imgg"
				src="{{ question.crossword.url }}"
				alt="Image is not available at this moment"
			/>
		</p>

		{% if question.hint %} {% if question.id == 1 %}

		<br />
		<!-- <div style="margin: 0 auto;max-width: 350px;height: 100px;border-radius: 3px;">
                
                <img style="width: 180px;height: 90px;float: left;"  src="{{ question.hint.url }}" alt="Image is not available at this moment">
                <p style="font-size: 25px; color: white;margin-top: 25px;" class="text-center"> cbjrwh</p>
               </div> -->
		<div
			style="
				margin: 0 auto;
				max-width: 500px;
				height: 150px;
				border-radius: 3px;
			"
		>
			<img
				class="pigpen"
				src="{{ question.hint.url }}"
				alt="Image is not available at this moment"
			/>
		</div>
		{% elif question.id == 2 %}

		<div
			style="
				margin: 10px auto;
				max-width: 350px;
				height: 130px;
				border-radius: 3px;
			"
		>
			<br />
			<audio
				style="margin-left: auto; margin-right: auto; display: block"
				controls
			>
				<source src="{{ question.hint.url }}" type="audio/mpeg" />
				Your browser does not support the audio element.
			</audio>
			<p style="font-size: 30px; color: white" class="text-center">
				.-. . -. -.. . --.. ...- --- ..- ...
			</p>
		</div>

		{% elif question.id == 4 %}
		<br />
		<div
			style="
				margin: 0 auto;
				max-width: 500px;
				height: 150px;
				border-radius: 3px;
			"
		>
			<img
				class="pigpen"
				src="{{ question.hint.url }}"
				alt="Image is not available at this moment"
			/>
		</div>
		{% elif question.id == 5 %}

		<br />
		<div
			style="
				margin: 0 auto;
				max-width: 500px;
				height: 150px;
				border-radius: 3px;
			"
		>
			<img
				class="pigpen"
				src="{{ question.hint.url }}"
				alt="Image is not available at this moment"
			/>
		</div>
		<p style="color: #fff" class="text-center">
			To get the key find hidden meaning of tnegkmdnr.<br />
			"Theory of Relativity" always bored you, but this time it will help you
			win.
		</p>
		{% endif %} {% endif %} {% if question.id == 3 or question.id == 7 %}
		<p style="color: #fff">{{ question.question|safe }}</p>
		{% endif %} {% if question.id == 6 %}
		<p style="color: white; font-size: 20px" class="text-center">
			Arrange the following words.
		</p>

		<form
			action=""
			method="post"
			id="upload_form"
			enctype="multipart/form-data"
		>
			{% csrf_token %}

			<label style="color: white" for="id_answer1"
				>BASEIB: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</label
			>
			<input
				type="text"
				name="answer1"
				maxlength="64"
				required=""
				id="id_answer1"
			/>
			<br />
			<label style="color: white" for="id_answer2"
				>ABSLT: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</label
			>
			<input
				type="text"
				name="answer2"
				maxlength="64"
				required=""
				id="id_answer2"
			/>
			<br />
			<label style="color: white" for="id_answer3">AAADONCN: &nbsp;</label>
			<input
				type="text"
				name="answer3"
				maxlength="64"
				required=""
				id="id_answer3"
			/>
			<br />
			<input
				type="submit"
				value="Submit"
				style="
					color: #fff;
					padding: 5px;
					height: 40px;
					width: 100px;
					border: 2px solid #fff;
				"
			/>
		</form>
		<br />
		<br />

		{% else %}

		<div
			style="
				margin: 0 auto;
				max-width: 300px;
				height: 100px;
				border-radius: 3px;
			"
		>
			<form
				style="
					color: black;
					display: block;
					margin-left: auto;
					margin-right: auto;
				"
				action=""
				method="post"
				id="upload_form"
				enctype="multipart/form-data"
			>
				{% csrf_token %}
				<input
					type="text"
					id="subject"
					name="answer"
					placeholder="Your Answer Here.."
					style="height: 40px; width: 250px; color: #fff"
				/>
				<input
					type="submit"
					value="Submit"
					style="
						color: #fff;
						padding: 5px;
						width: 100px;
						border: 2px solid #fff;
					"
				/>
			</form>
		</div>

		{% endif %}
	</div>
	{% if wrong == 1 %}
	<h4 style="color: red"><strong>Wrong Answer</strong></h4>
	{% endif %}
</div>

{% endblock %}