REChase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teams.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bit1/urls.py
from django.urls import path
from . import views

app_name = 'bit1'
urlpatterns = [
    path('', views.home, name='home'),
]

teams/urls.py
from django.urls import path, include
from . import views

app_name = 'teams'
urlpatterns = [
    path('', views.home, name='home'),
    path('get_team/', views.get_team, name='get-team'),
    path('create-team/', views.createTeam, name='create-team'),
    path('join-team/', views.joinTeam, name='join-team'),
    path('accept-team-mate/', views.acceptTeamMateView, name='accept-teammate'),
    path('complete-profile/', views.profileCompleteView, name='complete-profile'),
    path('scoreboard/', views.scoreboardView, name='scoreboard'),
    path('rules/', views.rules, name='rules'),
    path('playerdetail/', views.playerdetail, name='teamdetail'),
    path('detailedscore/',views.detailedScoreboardView, name='detailedscore'),
    path('chase/', views.get_level, name='get-level'),
    path('chase/1/', views.start_hunt, name='start_hunt'),

]

teams/models.py
import datetime
import json

from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import make_aware


class Team(models.Model):
    name = models.CharField(max_length=128, null=True, unique=True)
    code = models.CharField(max_length=128, null=True, blank=True)
    member_count = models.IntegerField(default=0, null=True)
    current_level = models.IntegerField(default=0, null=True)
    current_question = models.IntegerField(default=-1, null=True)
    question = models.CharField(max_length=255, null=True, blank=True, default='-1')
    answers = models.CharField(max_length=8192, null=True, blank=True, default='{}')
    score = models.IntegerField(default=0, null=True)
    rank = models.IntegerField(default=0, null=True)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def answerCorr(self, curr_lvl=1, answer=None):
        self.current_level = curr_lvl + 1
        self.current_question = -1
        self.question = '-1'
        self.score = self.score + 10
        if curr_lvl == 1:
            temp = {}
        else:
            temp = json.loads(self.answers)
        temp[curr_lvl] = answer
        self.answers = json.dumps(temp)
        self.timestamp = make_aware(datetime.datetime.now())
        self.save()

    

    def specialCipher(self, answer):
        temp = json.loads(self.answers)

        if self.current_question == 1:
            temp[str(self.current_level)] = {}
        temp[str(self.current_level)][str(self.current_question)] = answer

        self.answers = json.dumps(temp)
        if self.current_question == 7:
            self.current_level = self.current_level + 1
            self.current_question = -1
            self.question = '-1'
            self.score = self.score + 10
            self.timestamp = make_aware(datetime.datetime.now())

        else:
            self.current_question = self.current_question + 1

        self.save()




class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, null=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    phone = models.CharField(max_length=13, null=True)
    gender = models.CharField(max_length=2,
                              choices=(
                                  ('M', 'Male'),
                                  ('F', 'Female'),
                                  ('O', 'Others'),
                              ),
                              default='M')
    college = models.CharField(max_length=128, default='NIT Durgapur')
    team_code = models.CharField(max_length=128, null=True, blank=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    accepted = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.name

teams/forms.py
from django import forms

from .models import (
    Team,
    Player
)

class TeamCreationForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name']


class ProfileFillForm(forms.ModelForm):
    phone = forms.CharField(max_length=13, min_length=10)

    class Meta:
        model = Player
        fields = ['name', 'phone', 'gender', 'college']

teams/views.py
from django.shortcuts import render, redirect
from . import models
import datetime
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .decorators import team_required
from .forms import (
    TeamCreationForm,
    ProfileFillForm,
)
from .utils import makeCode
from django.conf import settings

def save_profile(backend, user, response, *args, **kwargs):
    # print(response)
    if backend.name == 'google-oauth2':
        profile = user
        try:
            Player = models.Player.objects.get(user=profile)
        except:
            Player = models.Player(user=profile)
            Player.timestamp = datetime.datetime.now()
            try:
                Player.name = response.get('name')
                Player.email = response.get('email')
            except:
                Player.name = response.get('given_name') + " " + response.get('family_name')
            Player.save()


def home(request):
    user = request.user
    if not user.is_authenticated:
        # For managing event Wait and Finish
        context = {}
        if datetime.datetime.now() < settings.START_TIME:
            context = {'wait': 1, 'cur_time': datetime.datetime.now(),
                       'start_time': settings.START_TIME}
        elif datetime.datetime.now() > settings.END_TIME:
            context['finish'] = 1
        else:
            context['started'] = 1
        return render(request, 'teams/base_menu.html', context)

    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect('teams:complete-profile')
    if profile.team is None or profile.accepted == 0:
        return render(request, 'teams/no_team.html', {})
    team = models.Team.objects.get(id=profile.team.pk)
    everyone = models.Player.objects.filter(team=team.pk)
    team_players = everyone.filter(accepted=1)
    context = {'team': team, 'profile': profile, 'players': team_players, 'max_level': settings.FINAL_LEVEL}
    if team.member_count < 5:
        applicants = everyone.filter(accepted=0)
        context['applicants'] = applicants

    # For managing event Wait and Finish  
    if datetime.datetime.now() < settings.START_TIME:
        context['wait'] = 1
        context['cur_time'] = datetime.datetime.now()
        context['start_time'] = settings.START_TIME
    elif datetime.datetime.now() > settings.END_TIME:
        context['finish'] = 1
    else:
        context['started'] = 1

    return render(request, 'teams/teamHome.html', context)

@login_required
@team_required
def get_level(request):
    user = request.user
    profile = models.Player.objects.get(user=user)

    team = models.Team.objects.get(id=profile.team.pk)
    level = team.current_level
    if level > settings.FINAL_LEVEL:
        return redirect('teams:scoreboard')

    return redirect(request.path + str(1))

@login_required
@team_required
def start_hunt(request):
    return render(request,'teams/start_location.html')



@login_required
def get_team(request):
    return render(request, 'teams/no_team.html', {})


@login_required
def createTeam(request):
    context = {}
    user = request.user
    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect('teams:complete-profile')
    form = TeamCreationForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        code = makeCode()
        obj.code = code
        obj.member_count = 1
        obj.save()
        curr_user = models.Player.objects.get(user=user)
        curr_user.team = obj
        curr_user.team_code = code
        curr_user.accepted = 1
        curr_user.save()
        return redirect('teams:home')

    context['form'] = form
    return render(request, 'teams/teamCreation.html', context=context)


@login_required
def joinTeam(request):
    context = {}
    user = request.user
    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect('teams:complete-profile')
    if profile.accepted == 1 and profile.team is not None:
        return redirect('teams:home')
    if request.method == 'POST':
        code = request.POST.get('code', -1)
        team = models.Team.objects.filter(code=code).first()
        if not team:
            context['wrong_code'] = 'Invalid code entered.'
            return render(request, 'teams/teamJoin.html', context=context)
        if team.member_count >= 5:
            context['team_full'] = 'Team is full.'
            return render(request, 'teams/teamJoin.html', context=context)
        profile.team = team
        profile.team_code = team.code
        profile.accepted = 0
        profile.save()
        context['sent'] = 1
        return render(request, 'teams/no_team.html', context=context)

    return render(request, 'teams/teamJoin.html', context=context)


@login_required
def profileCompleteView(request):
    context = {}
    user = request.user
    profile = models.Player.objects.get(email=user.email)
    form = ProfileFillForm(request.POST or None)
    if form.is_valid():
        form.clean()
        profile.name = form.cleaned_data['name']
        profile.phone = form.cleaned_data['phone']
        profile.gender = form.cleaned_data['gender']
        profile.college = form.cleaned_data['college']
        profile.save()
        return redirect('teams:home')
    context['form'] = form
    return render(request, 'teams/createProfile.html', context)


@login_required
@team_required
def leaveTeamView(request):  # needs to be removed
    context = {}
    user = request.user
    profile = models.Player.objects.get(user=user)
    team = models.Team.objects.get(id=profile.team.pk)
    if request.method == 'POST':
        if team.member_count == 1:
            team.delete()
        else:
            team.member_count = team.member_count - 1
            team.save()
        profile.team = None
        profile.team_code = None
        profile.save()
        return redirect('teams:get-team')
    context['team'] = team
    context['profile'] = profile
    return render(request, 'teams/confirmLeave.html', context)


@login_required
def acceptTeamMateView(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('/oauth/login/google-oauth2/')

    profile = models.Player.objects.get(user=user)
    if profile.phone is None:
        return redirect(reverse_lazy('teams:complete-profile'))

    if profile.accepted == 0 or profile.team is None:
        return redirect(reverse_lazy('teams:get-team'))

    context = {}
    owner = models.Player.objects.get(user=request.user)
    team = models.Team.objects.get(pk=owner.team.id)
    applicantId = int(request.POST.get('ID'))
    verdict = request.POST.get('verdict')
    applicant = models.Player.objects.get(id=applicantId)
    if verdict == 'Reject':
        applicant.team = None
        applicant.save()
    elif verdict == 'Accept':
        if team.member_count >= 5:
            context['team_full'] = 'Team is full.'
            return redirect('teams:home')
        applicant.accepted = 1
        applicant.team_code = team.code
        applicant.save()
        team.member_count = team.member_count + 1
        team.save()
    return redirect('teams:home')


def scoreboardView(request):
    context = {'cur_time': datetime.datetime.now(), 'start_time': settings.START_TIME}

    cur_rank = 0
    try:
        all_teams = models.Team.objects.all()
        qs = all_teams.order_by('-score', 'timestamp')
        for pl in qs:
            pl.rank = cur_rank
        context['qs'] = qs
    except:
        context['wrong'] = 1
    if datetime.datetime.now() < settings.START_TIME:
        context['wait'] = 1
    return render(request, 'teams/leaderBoard.html', context)


def rules(request):
    context = {}
    return render(request, 'teams/rules.html', context)


def playerdetail(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("teams:home"))
    if not request.user.is_superuser:
        return redirect(reverse_lazy("teams:home"))
    all_players = models.Player.objects.all().order_by('-team_code', 'timestamp')
    context = {'players': all_players}
    return render(request, 'teams/playerdetail.html', context)

def detailedScoreboardView(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy("teams:home"))
    if not request.user.is_superuser:
        return redirect(reverse_lazy("teams:home"))
    
    context = {'cur_time': datetime.datetime.now(), 'start_time': settings.START_TIME}

    cur_rank = 0
    
    all_teams = models.Team.objects.all()
    qs = all_teams.order_by('-score', 'timestamp')
    allplayers = models.Player.objects.all()
    qp = []
    for pl in qs:
        pl.rank = cur_rank
        tc = pl.code
        sz = pl.member_count
        players = []
        for eachplayer in allplayers:
            teamcode = eachplayer.team_code
            if teamcode == tc:
                players.append({
                    "name" : eachplayer.name,
                    "email" : eachplayer.email,
                })
        cnt_player = 1 
        player1 = "-"
        player2 = "-"
        email1 = "-"
        email2 = "-"
        for xx in players:
            if cnt_player==1:
                player1 = xx["name"]
                email1 = xx["email"]
            if cnt_player==2:
                player2 = xx["name"]
                email2 = xx["email"]
            cnt_player+=1
        
        qp.append(
            {
                "rank" : cur_rank,
                "name" : pl.name,
                "score" : pl.score,
                "ques" : pl.current_level,
                "player1" : player1,
                "player2" : player2,
                "email1" : email1,
                "email2" : email2
            }
        )
        # cur_rank += 1
        context['qp'] = qp
        leveldetail=[]
        for i in range(1,13):
            curr_level = i

teams/templates/teams/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>
    {% block title %}
        REChase
    {% endblock %}
</title>

<link rel="shortcut icon" type="image/png" href="{% static 'teams/images/favicon.png' %}"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<style>
    p{
        font-size: 2em;
        word-wrap: break-word;
    }
   
    img {
        border: 5px solid #555;
        width: 100%;
        height: auto;
    }
</style>
{% block head %} {% endblock %}

</head>
<body>
{% include 'teams/snippets/navbar.html' %}
{% block content %}
{% endblock %}
{% block footer %}{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

teams/templates/teams/confirmLeave.html
{% extends 'teams/base_bootstrap.html' %}

{% block title %}
Are you sure you wanna LEAVE team?
{% endblock title %}

{% block content %}

    <style type="text/css">
  .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
        margin-top: 80px;

    }

</style>


    <div class="col-sm-6 col-sm-offset-3 text-center create-form">
        <form class="create-form" method="POST" action="{% url 'teams:leaveTeam' %}">{% csrf_token %}
            <h1>Confirm leaving team?</h1>
            <p>You sure you wanna LEAVE <a href="{% url 'teams:home' %}">{{ team.name }}</a>?
            </p>

            <input type="submit" value="Confirm Leave" class="btn btn-info">
            <a href="{% url 'teams:home' %}" class="btn btn-default">Cancel</a>
        </form>

    <hr/>
    </div>

{% endblock content %}

teams/templates/teams/createProfile.html
{% extends 'teams/base_bootstrap.html' %}
{% load crispy_forms_field %}
{% block title %}
    Complete profile
{% endblock %}

{% block content %}

<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <style>
        .container {
            padding-top: 5vh;
            position: relative;
            display: flex;
            justify-content: center;
            align-items: center;

        }

        .container .box {
            /* backdrop-filter: blur(5px); */
            position: relative;
            width: 500px;
            height: 400px;
            color: #010203;
            display: flex;
            justify-content: center;
            align-items: center;
            /*webkit-box-reflect:below 15px linear-gradient(transparent,transparent,rgba(0,0,0,.2));*/
        }

        /* .container .box:hover{

        } */
        .container .box:before {
            background: rgba(1, 2, 3, 0.6);
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 110%;
            /* border:4px solid #fff;
            background:rgba(225,225,225,.1);
            filter: url(#wavy); */
            border: 4px groove transparent;
            border-radius: 5%;
        }

        .container .box .content {
            position: absolute;
            text-align: center;
            transition: 0.5s;
        }

        .container .box:after {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 0%;
            height: 100%;
            /* border: 4px solid #fff;
            background:rgba(225,225,225,.1);
            border-right: none;
            filter: url(#wavy); */
        }

        .container .box h1 {
            font-family: 'MedievalSharp', cursive;
            font-size: 4rem;
            font-weight: bold;
            color: #fff;

        }

        .container .box p {
            color: #fff
        }

        .container .box .form {
            margin-top: 2rem;
        }

        input[type=submit] {
            background: -webkit-gradient(linear, left bottom, left top, from(#000000), to(#262626));
            background: -webkit-linear-gradient(bottom, #000000, #262626);
            background: -moz-linear-gradient(bottom, #000000, #262626);
            background: -o-linear-gradient(bottom, #000000, #262626);
            background: linear-gradient(0deg, #000000, #262626);
            color: blue; backdrop-filter: blur(10 px); padding: 25 px 105 px; border: none; border-radius: 10 px; cursor: pointer; box-shadow: 0 0 1 rem 0 rgba(0, 0, 0, .4);

        }

        input[type=text], select, textarea {
            width: 14em;
            padding: 8px;
            border: 2px solid #fff;
            border-radius: 10px;
            box-sizing: border-box;
            margin-top: 6px;
            margin-bottom: 16px;
            resize: vertical;

            color: #fff;
            background: -webkit-gradient(linear, left bottom, left top, from(#000000), to(#262626));
            background: -webkit-linear-gradient(bottom, #000000, #262626);
            background: -moz-linear-gradient(bottom, #000000, #262626);
            background: -o-linear-gradient(bottom, #000000, #262626);
            background: linear-gradient(0deg, #000000, #262626);
            backdrop-filter: blur(10px);
        }

        @media only screen and (max-width: 600px) {
            .container {
                padding-top: 100px;
            }

            .container .box {
                width: 90% !important;

            }

            .container .box .content {
                font-size: 15px;

            }
        }

        @import url('https://fonts.googleapis.com/css2?family=Metrophobic&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Niconne&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Audiowide&family=Orbitron&display=swap');


        .main-wrapper {
            position: absolute;
            margin-top: 100px;
            width: 100%;
            height: 100%;
            left: 0 !important;
            top: 0 !important;

        }


        @media (max-width: 500px) {
            .main-wrapper {
                margin-top: 70px;
            }
        }

        #id_gender .female {
            background-color: black;
            background: linear-gradient(0deg, #000000, #262626);
        }

        label {
            font-size: 16.5px;
        }
    </style>

    <div class="container">

        <div class="box">
            <div class="content">

                <form method="POST">{% csrf_token %}
                    <p style="font-size: 2rem;margin-top:50px; color: white;font-family: 'Orbitron', sans-serif;" class="text-center">
                        Complete your
                        profile.</p>

                    <table style="color: white; margin: auto;padding: 10px;">
                        <table style="color: white; margin: auto;padding: 10px;">
                            <tbody>
                            <tr>
                                <th><label for="id_name">Name:</label></th>
                                <td><input type="text" name="name" maxlength="128" required="" id="id_name"></td>
                            </tr>
                            <tr>
                                <th><label for="id_phone">Phone:</label></th>
                                <td><input type="text" name="phone" maxlength="13" minlength="10" pattern="\d{10}" required=""
                                           id="id_phone"></td>
                            </tr>
                            <tr>
                                <th><label for="id_gender">Gender:</label></th>
                                <td><select name="gender" id="id_gender">
                                    <option value="M" selected="" style="background:black">Male</option>

                                    <option value="F" style="background:black">Female</option>

                                    <option value="O" style="background:black"> Others</option>

                                </select></td>
                            </tr>
                            <tr>
                                <th><label for="id_college">Institute: </label></th>
                                <td><input type="text" name="college" value="NIT Durgapur" maxlength="128" required=""
                                           id="id_college"></td>
                            </tr>
                            </tbody>
                        </table>

                    </table>

                    </p>
                    <input class="btn btn-primary"
                           style="color: #fff;padding:5px;height:40px;width:100px;border: 2px solid #fff;font-family: 'Orbitron', sans-serif;"
                           type="submit" value="Save">
                    </p>
                </form>

            </div>
        </div>
    </div>


{% endblock %}

teams/templates/teams/no_team.html
{% include 'teams/base_bootstrap.html' %}
{% load static %}
{% block content %}
  <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
 <script src="https://kit.fontawesome.com/a076d05399.js"></script>
 <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">

 <style>
  .container{
  padding-top: 5vh;
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;

}
.container .box{
  /* backdrop-filter: blur(5px); */
  position: relative;
  width: 500px;
  height: 400px;
  color: white;
  display: flex;
  justify-content: center;
  align-items: center;
  /*webkit-box-reflect:below 15px linear-gradient(transparent,transparent,rgba(0,0,0,.2));*/
}

.container .box:before{
  background: rgba(1, 2, 3,0.6);
  content: '';
  position: absolute;
  top:0;
  left:0;
  width: 100%;
  height: 100%;
  /* border:4px solid #fff;
   background:rgba(225,225,225,.1);
  filter: url(#wavy); */
  border: 4px groove transparent;
  border-radius:5%;
}
.container .box .content{
position:absolute;
padding: 20px;
text-align: center;
transition: 0.5s;
}
.container .box:after{
content: '';
position: absolute;
top:0;
left:0;
width:0%;
height: 100%;
/* border: 4px solid #fff;
background:rgba(225,225,225,.1);
border-right: none;
filter: url(#wavy); */
}

.container .box h1{
  font-family: 'MedievalSharp', cursive;
  font-size: 4rem;
  font-weight: bold;
  color: #fff;

}
.container .box p{
color: #fff
}

.container .box .form{
  margin-top: 2rem;
}

.container .box .content{
 padding-left: 10%;
}




#subject{

  padding-right:10% ;
}

@import url('https://fonts.googleapis.com/css2?family=Metrophobic&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Niconne&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Audiowide&display=swap');



.main-wrapper {
position: absolute;
margin-top: 100px;
  width: 100%;
  height: 100%;
  left :0!important;
  top:0!important;

}
</style>

<div class="container">
  <div class="box">
    <div class="content">
      {% if sent %}
      <p style="color: white; letter-spacing: 2px; font-family: 'Orbitron', sans-serif;font-size:20px;">
        Request sent !! Ask team creator to reload team page!!
      </p>
        {% endif %}
      <h1 style="text-align: center;">
        <a  style="text-decoration: none ; color: #fff;font-size: 35px;     font-family: 'orbitron', sans-serif !important;"   href="{% url 'teams:create-team' %}">Create team</a>
      </h1>
        <br>
      <h1 style="text-align: center;">
        <a style="text-decoration: none ; color: #fff;font-size: 35px;    font-family: 'orbitron', sans-serif !important;" href="{% url 'teams:join-team' %}">Join team</a>
      </h1>
    </div>
  </div>
</div>



{% endblock %}

teams/templates/teams/teamHome1.html
{% extends "teams/base_bootstrap.html" %}

{% block content %}

<style>
    a:link {
      color: green;
      background-color: transparent;
      text-decoration: none;
    }
    a:visited {
      color: rgb(252, 0, 42);
      background-color: transparent;
      text-decoration: none;
    }
    a:hover {
      color: red;
      background-color: transparent;
      text-decoration: underline;
    }
    a:active {
      color: rgb(0, 255, 85);
      background-color: transparent;
      text-decoration: underline;
    }
    @import url('https://fonts.cdnfonts.com/css/fast-hand');
    </style>

    
<p style="color: white;">
    <h2 style="color: white;" class="text-center">Team Details</h2>
    <br>
    <p>
        <h4 style="color: white;" class="text-center"><a href="{% url 'teams:get-level' %}">Play</a></h4>
        
        <h4  style="color: white;"class="text-center">Team Name: {{team.name}}</h4>
        
        <h4 style="color: white;" class="text-center">Team Code: {{team.code}}</h4>
        
        <h4 style="color: white;" class="text-center">Score: {{team.score}}</h4>
        
        <h4 style="color: white;" class="text-center">Current level:
        {% if  team.current_level > max_level  %}
            {{ max_level }}
        {% else %}
            {{ team.current_level }}
        {% endif %}
        </h4>
    </p>
    <br>
    <h2 style="color: white;" class="text-center">Team Members</h2>
    <br>
    {% for player in players %}
        <ul style="color: white;" class="text-center">{{player}} :: {{player.email}}</ul><br>
    {% endfor %}
   {# <a style="color: white;" class="text-center" href="{% url 'teams:leaveTeam' %}">Leave team.</a>#}
    {% if applicants %}
        <h2 style="color: white;" class="text-center">Applicants</h2>
        <ul>
            {% for applicant in applicants %}
                <li style="color: white;" class="text-center">
                    <form method="post" action="{% url 'teams:accept-teammate' %}">{% csrf_token %}
                        <h4 class="text-center">{{ applicant.name }}({{ applicant.email }})</h4>
                        <input type="hidden" name="ID" value="{{ applicant.id }}"/>
                        <input type="submit" name="verdict" value="acc">
                        <input type="submit" name="verdict" value="rej">
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <p>

{% endblock %}